head(airquality)
tail(airquality)
summary(airquality)
summary(airquality$Wind)
plot(airquality$Wind)
plot(airquality$Temp,airquality$Wind,type = "b")
plot(airquality$Temp,airquality$Wind,type = "l")
plot(airquality$Temp,airquality$Wind,type = "p")
barplot(airquality$Wind,main = "barplot",ylab = "ozone level",col = 'blue',horiz = F,axes = T)
hist(airquality$Temp)
hist(airquality$Solar.R,main = 'value in air',xlab = 'solar rad',col = 'blue')
boxplot(airquality$Wind,main="Boxplot")
summary(airquality$Wind)
boxplot(airquality[,1:4],main="multuple")
#margin of the grid(mar)
#no of rows and columns(mfrow)
#whether a border is to be included(bty)
par(mfrow=c(3,3),mar=c(2,5,2,1),las=0,bty="o")
plot(airquality$Ozone)
plot(airquality$Ozone,airquality$Wind)
plot(airquality$Ozone,type = "l")
plot(airquality$Ozone,type = "l")
barplot(airquality$Ozone, main = 'ozone consecentretedin air',xlab='ozone level',col='green',horiz='TRUE')
hist(airquality$Solar.R)
boxplot(airquality$Solar.R)
boxplot(airquality[,1:4],main='multiple box plot')
